### ISSUE TITLE
times out and causes test failures in nbb

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-package-manager#32]
1) Admin Controllers
       should load /admin/extend/plugins:
     Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/NodeBB/NodeBB/test/controllers-admin.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

**Comment by barisusakli** [comment]
Cached trending packages 
https://github.com/NodeBB/nodebb-package-manager/commit/a5f15814e05f77410d7f13b6111f7e40ca57f895

Real issue seems to be the zsets used to generate trending plugins contain 2300 packages, ie `'analytics:' + key + ':daily'` and they seem to be populated everytime suggest is called since we can't check if someone really installed a plugin.

The slow parts are here https://github.com/NodeBB/nodebb-package-manager/blob/master/lib/analytics.js#L126-L132.

2300 keys * 7 days multi.zscore calls as more and more plugins get published it gets slower even though some of these plugins are never installed in the past 7 days they are still in the zset `'analytics:' + key + ':daily'`
